server:
  port: 8090

datasource:
  driverName: mysql
  name: root
  password: root
  host: localhost
  port: 3306
  database: auth_frame
  charset: utf8

redis:
  size: 10
  network:  tcp
  address:  127.0.0.1:6379
  password: root
  key:  secret

swagger:
  title: auth_frame swagger API
  desc: This is a frame
  host: 127.0.0.1:8090
  base_path:


